config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :contacts
  root to: "home#index"
  get "home/index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: { firefox: 115, chrome: 118 }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_model!, except: [ :index ]
  before_action :correct_user, only: [ :edit, :update, :destroy  ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    # @contact = Contact.new
    @contact = current_model.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    # @contact = Contact.new(contact_params)
    @contact = current_model.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # function to define actions, "FCC: 'learn RoR - Full course'" at 2:58:00
  def correct_user
    @contact = current_model.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Action Not Authorized" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :instagram, :model_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <tr>
    
    <td>
      <strong>Name:</strong>
      <%= link_to contact.first_name + ' ' + contact.last_name, contact %>
    </td>

    <td>
      <strong>Email:</strong>
      <%= contact.email %>
    </td>

    <td>
      <strong>Phone:</strong>
      <%= contact.phone %>
    </td>

    <td>
      <strong>Instagram:</strong>
      <%= contact.instagram %>
    </td>

    <%#    <td>
      <strong>User(model):</strong>
      <%= contact.model_id %>
    </td>
 
  </tr>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.number_field :model_id, id: :contact_model_id, class:"form-control", value: current_model.id, type: :hidden %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<table class="table table-hover table-bordered table-sm">
  <%# link_to "Show this contact", @contact, class:"btn btn-secondary btn-sm" %> 
  <%= button_to "Destroy this contact", @contact, method: :delete, class:"btn btn-danger btn-sm" %> |
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contacts" %>


<table class="table table-striped table-bordered table-hover table-reponsive">
  <thead class="table-dark">
    <% @contacts.each do |contact| %>
    <% if contact.model == current_model %>  
      <tbody>
        <tr>
          <td>
            <%= link_to contact.first_name + ' ' + contact.last_name, contact %>
          </td>
        </tr>
      </tbody>
    <% end %>
  <% end %>
</table>

<%= link_to "New contact", new_contact_path, class:"btn btn-primary" %>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <p class="display-4"><%= render @contact %></p>
  
  <%= link_to "Edit this contact", edit_contact_path(@contact), class:"btn btn-secondary" %> |
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-dark" %> |
  <br>
  <%= button_to "Destroy this contact", @contact, method: :delete, class:"btn btn-danger btn-sm"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'app to learn', root_path, class:"navbar-brand"  %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if model_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Contacts', contacts_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_model_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign OUT', destroy_model_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to 'Sign IN', new_model_session_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign UP', new_model_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
      <% end %>

  </div>
</nav>

app/views/home/about.html.erb
<h1>Hello fucking World!</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my second Rails Webpage...

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>App to learn Ruby on Rails with freeCodeCamp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= yield :head %>

      <link rel="manifest" href="/manifest.json">
      <link rel="icon" href="/icon.png" type="image/png">
      <link rel="icon" href="/icon.svg" type="image/svg+xml">
      <link rel="apple-touch-icon" href="/icon.png">
      <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>